# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_search', '0003_auto_20171003_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_name',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
