# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_search', '0004_auto_20171003_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default=b'None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default=b'None', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, default=b'None', max_length=30, null=True),
        ),
    ]
