# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_search', '0005_auto_20171003_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_record_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
